import type { FC, ReactNode } from 'react';
import 'sanitize.css';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body>
      {children}
    </body>
  </html>
);

export default RootLayout;
